global:
  repo: https://github.com/luqasn/ArgoCD-SCALE.git
  branch: main
  domain: luqasn.org
  altDomainHome: bruns.house
  TZ: Europe/Berlin

  applicationSets:
  - common
  # - media
  # - home
  # - monitoring
    
  storage:
    pools: 
      argo-zfspv-fast: luna/argo/pv
      argo-zfspv-slow: andromeda/argo/pv
