# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
kube-prometheus-stack:
  fullnameOverride: kps
  
  alertmanager:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      paths:
        - /
      hosts:
      - 'alertmanager.internal.{{ .Values.global.domain }}'
      tls:
        - secretName: 'alertmanager-tls'
          hosts:
            - 'alertmanager.internal.{{ .Values.global.domain }}'

  prometheus:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      paths:
        - /
      hosts:
      - 'prometheus.internal.{{ .Values.global.domain }}'
      tls:
        - secretName: 'prometheus-tls'
          hosts:
            - 'prometheus.internal.{{ .Values.global.domain }}'
    
    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#prometheusioscrape
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: argo-zfspv-fast
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

  prometheus-node-exporter:
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
  
  # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  grafana:
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      paths:
        - /
      hosts:
      - 'grafana.internal.{{ .Values.global.domain }}'
      tls:
        - secretName: 'grafana-tls'
          hosts:
            - 'grafana.internal.{{ .Values.global.domain }}'

    persistence:
      enabled: true
      storageClassName: argo-zfspv-fast

    admin:
      existingSecret: grafana-admin

    defaultDashboardsTimezone: browser
    
    plugins:
      - grafana-piechart-panel

    grafana.ini:
      server:
        root_url: 'https://grafana.internal.{{ .Values.global.domain }}'
